### ISSUE TITLE
Error writing primers to file

### ISSUE THREAD

**Issue by jfreimer** [maximilianh/crisporWebsite#25]
I am trying to generate amplicon primers for guide RNAs. I am running the following command: 
`python crispor.py hg38 sampleFiles/test/input.fa sampleFiles/test/output.tsv --satMutDir=sampleFiles/test/ -d`

and getting the following error. I have looked in the primer3Out.txt file and the primers are there, but they are not getting processed and written properly in the next steps.

`DEBUG:root:Running set -o pipefail; /scratch/groups/pritch/jake/crispor/crisporWebsite/bin/Linux/primer3_core /tmp/primer3In.txt > /tmp/primer3Out.txt
INFO:root:Writing primers to sampleFiles/test/seq1_ontargetPrimers.tsv
DEBUG:root:reading offtargets from /tmp/crisporpLUEKA/FuOwg3SoSc4U3oJnIDkt.bed.gz
Traceback (most recent call last):
  File "crispor.py", line 8266, in <module>
    main()
  File "crispor.py", line 8264, in main
    mainCommandLine()
  File "crispor.py", line 8109, in mainCommandLine
    writeOntargetAmpliconFile("primers", batchId, options.ampLen, options.tm, pFh)
  File "crispor.py", line 5681, in writeOntargetAmpliconFile
    effScores = allEffScores[pamId]
KeyError: 's20+'`

**Comment by jfreimer** [comment]
Found the issue, it was doing to have NGG in the input fasta.
