### ISSUE TITLE
dbm problems

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/crisporWebsite#37]
From Jubina Benny:

When I try running the example command:
python crispor.py sacCer3 sampleFiles/in/sample.sacCer3.fa sampleFiles/mine/sample.sacCer3.tsv -o sampleFiles/mine/sample.sacCer3.mine.offs.tsv

I get this error:

Traceback (most recent call last):
  File "crispor.py", line 8458, in <module>
    main()
  File "crispor.py", line 8455, in main
    mainCommandLine()
  File "crispor.py", line 8264, in mainCommandLine
    getOfftargets(seq, org, pamPat, batchId, startDict, ConsQueue())
  File "crispor.py", line 4377, in getOfftargets
    processSubmission(faFname, org, pamDesc, otBedFname, batchBase, batchId, queue)
  File "crispor.py", line 3912, in processSubmission
    createBatchEffScoreTable(batchId, queue)
  File "crispor.py", line 3515, in createBatchEffScoreTable
    guideRows = calcSaveEffScores(batchId, seq, extSeq, pam, queue)
  File "crispor.py", line 3457, in calcSaveEffScores
    saveOutcomeData(batchId, mutScores)
  File "crispor.py", line 4254, in saveOutcomeData
    import dbm
ImportError: No module named dbm

**Comment by maximilianh** [comment]
python 2.7.15

**Comment by maximilianh** [comment]
she writes: I found a way.

I re-write the import dbm in crispor.py (line number 4254) to import gdbm
and line number 4255 to gdbm.open

because for this definition (saveoutcomedata) there is no try and except given as given in the readoutcomedata.



and its working fine.

**Comment by tiramisutes** [comment]
Besides `dbm`, the `tensorflow` and `theano` packages are still difficult to install for python2.7 when cpf1 PAM is used, whether to use pip or conda. Maybe python3.6 is more best if this software can update to support for py3.6.

**Comment by maximilianh** [comment]
I'm sorry, but upgrading this software to python3 will probably not be
easy. I installed theano and tensorflow without too much trouble. Where did
you run into issues?

**Comment by geraldocantelli** [comment]
Hello, I am having the same problem but the suggestion above (replace in the lines 4254 and 4255) didn't work for me:
This is what happened:
sudo python ./crispor.py sacCer3 sampleFiles/in/sample.sacCer3.fa sampleFiles/mine/sample.sacCer3.tsv -o sampleFiles/mine/sample.sacCer3.mine.offs.tsv
INFO:root: * running on sequence 'testSeq', guideLen=20, seqLen=182
INFO:root:Progress x50sPGMoTvUagv3zWjGg - bwasw - Searching genome for one 100% identical match to input sequence
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[bsw2_aln] read 1 sequences/pairs (182 bp) ...
[main] Version: 0.7.15-r1140
[main] CMD: /var/www/html/crisporWebsite/bin/Linux/bwa bwasw -b 100 -q 100 -T 20 /var/www/html/crisporWebsite/genomes/sacCer3/sacCer3.fa /tmp/primer3In43P4iZ.txt
[main] Real time: 0.030 sec; CPU: 0.028 sec
INFO:root:Progress x50sPGMoTvUagv3zWjGg - effScores - Calculating guide efficiency scores
Traceback (most recent call last):
  File "./crispor.py", line 8617, in <module>
    main()
  File "./crispor.py", line 8614, in main
    mainCommandLine()
  File "./crispor.py", line 8423, in mainCommandLine
    getOfftargets(seq, org, pamPat, batchId, startDict, ConsQueue())
  File "./crispor.py", line 4463, in getOfftargets
    processSubmission(faFname, org, pamDesc, otBedFname, batchBase, batchId, queue)
  File "./crispor.py", line 3988, in processSubmission
    createBatchEffScoreTable(batchId, queue)
  File "./crispor.py", line 3590, in createBatchEffScoreTable
    guideRows = calcSaveEffScores(batchId, seq, extSeq, pam, queue)
  File "./crispor.py", line 3527, in calcSaveEffScores
    effScores = crisporEffScores.calcAllScores(longSeqs, enzyme=enz, scoreNames=scoreNames)
  File "/var/www/html/crisporWebsite/crisporEffScores.py", line 933, in calcAllScores
    scores["fusiOld"] = calcFusiDoench(trimSeqs(seqs, -24, 6))
  File "/var/www/html/crisporWebsite/crisporEffScores.py", line 1174, in calcFusiDoench
    model= pickle.load(f) # if this fails, install sklearn like this: pip install scikit-learn==0.16.1
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'PresortBestSplitter'

Could some one help me please?
Best regards, 
Geraldo Cesar Cantelli

**Comment by maximilianh** [comment]
Do you have sklearn installed ?

**Comment by maximilianh** [comment]
These problems should all be solved now with the upgrade to python3 of the entire crispor source code.
