### ISSUE TITLE
crisprAddGenome bug

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/crisporWebsite#38]
From Jubina Benny:

INFO:root:converting genePred to segment names: cat /tmp/MusaPhahang/MusaPhahang.gp | awk 'BEGIN {FS=OFS="      ";} // { gsub(" " , "_", $1); gsub(" ", "_", $12); print }' | genePredToBed stdin stdout | python bedToExons stdin stdout | sort -u | bedSort stdin stdout | python bedOverlapMerge /dev/stdin /dev/stdout | python bedBetween stdin /dev/stdout -a -s /tmp/MusaPhahang/MusaPhahang.sizes | bedSort stdin /tmp/MusaPhahang/MusaPhahang.segments.bed
INFO:root:Running: ['/bin/bash', '-e', '-o', 'pipefail', '-c', 'cat /tmp/MusaPhahang/MusaPhahang.gp | awk \'BEGIN {FS=OFS="\t";} // { gsub(" " , "_", $1); gsub(" ", "_", $12); print }\' | genePredToBed stdin stdout | python bedToExons stdin stdout | sort -u | bedSort stdin stdout | python bedOverlapMerge /dev/stdin /dev/stdout | python bedBetween stdin /dev/stdout -a -s /tmp/MusaPhahang/MusaPhahang.sizes | bedSort stdin /tmp/MusaPhahang/MusaPhahang.segments.bed']
  File "bedToExons", line 1
SyntaxError: Non-ASCII character '\x88' in file bedToExons on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "bedOverlapMerge", line 67, in <module>
    printLine(lastChrom, lastStart, lastEnd, names)
  File "bedOverlapMerge", line 28, in printLine
    print "\t".join(row)
TypeError: sequence item 0: expected string, NoneType found
Reading beds ...
Reading stdin...
0 features read
Traceback (most recent call last):
  File "bedBetween", line 313, in <module>
output(outf, None, beds[0], upstream, limit, "ig", chromSize)
IndexError: list index out of range
Could not run command cat /tmp/MusaPhahang/MusaPhahang.gp | awk 'BEGIN {FS=OFS="        ";} // { gsub(" " , "_", $1); gsub(" ", "_", $12); print }' | genePredToBed stdin stdout | python bedToExons stdin stdout | sort -u | bedSort stdin stdout | python bedOverlapMerge /dev/stdin /dev/stdout | python bedBetween stdin /dev/stdout -a -s /tmp/MusaPhahang/MusaPhahang.sizes | bedSort stdin /tmp/MusaPhahang/MusaPhahang.segments.bed

**Comment by maximilianh** [comment]
With python3, this problem never appeared. Looks OK.
