### ISSUE TITLE
crispor.py command fails on the test dataset

### ISSUE THREAD

**Issue by aayushraman** [maximilianh/crisporWebsite#58]
I installed all software and python packages on the centos linux platform using miniconda3. 

```unix
> uname --kernel-name --kernel-release --machine
Linux 3.10.0-1160.66.1.el7.x86_64 x86_64

> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

> conda --version
conda 22.9.0
```

I tested the crispor.py by running the following command provided in the [README file](https://github.com/maximilianh/crisporWebsite#readme).

```unix
> ./crispor.py sacCer3 sampleFiles/mine/sample.sacCer3.fa sampleFiles/mine/sample.sacCer.tsv -o sampleFiles/mine/test_run.tsv

INFO:root: * running on sequence 'testSeq', guideLen=20, seqLen=182
INFO:root:Progress x50sPGMoTvUagv3zWjGg - bwasw - Searching genome for one 100% identical match to input sequence
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[bsw2_aln] read 1 sequences/pairs (182 bp) ...
[main] Version: 0.7.15-r1140
[main] CMD: /aryeelab/aayushraman/crisporWebsite/bin/Linux/bwa bwasw -b 100 -q 100 -T 20 /aryeelab/aayushraman/crisporWebsite/genomes/sacCer3/sacCer3.fa /tmp/primer3Invk1AD7.txt
[main] Real time: 0.029 sec; CPU: 0.027 sec
INFO:root:Progress x50sPGMoTvUagv3zWjGg - effScores - Calculating guide efficiency scores
Traceback (most recent call last):
  File "./crispor.py", line 8726, in <module>
    main()
  File "./crispor.py", line 8723, in main
    mainCommandLine()
  File "./crispor.py", line 8524, in mainCommandLine
    getOfftargets(seq, org, pamPat, batchId, startDict, ConsQueue())
  File "./crispor.py", line 4523, in getOfftargets
    processSubmission(faFname, org, pamDesc, otBedFname, batchBase, batchId, queue)
  File "./crispor.py", line 4045, in processSubmission
    createBatchEffScoreTable(batchId, queue)
  File "./crispor.py", line 3647, in createBatchEffScoreTable
    guideRows = calcSaveEffScores(batchId, seq, extSeq, pam, queue)
  File "./crispor.py", line 3584, in calcSaveEffScores
    effScores = crisporEffScores.calcAllScores(longSeqs, enzyme=enz, scoreNames=scoreNames)
  File "/aryeelab/aayushraman/crisporWebsite/crisporEffScores.py", line 927, in calcAllScores
    scores["fusi"] = calcAziScore(trimSeqs(seqs, -24, 6))
  File "/aryeelab/aayushraman/crisporWebsite/crisporEffScores.py", line 1149, in calcAziScore
    import azimuth.model_comparison
  File "/aryeelab/aayushraman/crisporWebsite/bin/Azimuth-2.0/azimuth/model_comparison.py", line 1, in <module>
    import azimuth.predict as pd
  File "/aryeelab/aayushraman/crisporWebsite/bin/Azimuth-2.0/azimuth/predict.py", line 3, in <module>
    from sklearn.metrics import roc_curve, auc
  File "/aryeelab/aayushraman/bin/virtual_env/crispor/lib/python2.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/aryeelab/aayushraman/bin/virtual_env/crispor/lib/python2.7/site-packages/sklearn/metrics/ranking.py", line 26, in <module>
    from ..utils import check_consistent_length
  File "/aryeelab/aayushraman/bin/virtual_env/crispor/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "numpy.pxd", line 861, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5033)

ValueError: numpy.ufunc has the wrong size, try recompiling
```
I am getting the numpy.ufunc error. Can you please help? Thanks!

Best,
-Ar

**Comment by maximilianh** [comment]
Hi, sorry, I've never had this error. Did you try doing what the error
message says "recompiling" ? This sounds like a conda problem. Is there a
reason why you didn't install numpy via the normal packages?

**Comment by aayushraman** [comment]
I was able to solve the issue by first installing the **numpy=1.16.0** package (`pip install --no-deps --upgrade numpy==1.16.0`) and then **python-gdbm**  package from conda (`conda install --no-deps -c free python-gdbm`). 

Here is my env:

```
channels:
  - free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cycler=0.10.0=py27_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - pip=19.3.1=py27_0
  - python=2.7.18=ha1903f6_2
  - python-gdbm=1.1=py27_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=44.0.0=py27_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - numpy==1.16.0
    - pandas==0.23.4
    - py==1.4.31
    - python-dateutil==2.6.0
    - scikit-learn==0.16.1
    - tk==0.1.0
```

Best,
-Ar
