### ISSUE TITLE
File "../bin/samToBed", line 14, in <module> IndexError: list index out of range

### ISSUE THREAD

**Issue by elijahlowe** [maximilianh/crisporWebsite#9]
I am receiving the following area and can not figure out the problem. I'm running the cold on the test data.

```
../crispor.cgi sacCer3 sampleIn.fa sampleOut.mine.tsv -o sampleOutOfftargets.mine.tsv
INFO:root:running on sequence ID 'testSeq'
[bsw2_aln] read 1 sequences/pairs (182 bp) ...
[main] Version: 0.7.9a-r786
[main] CMD: /Users/elowe3/bioinformatics_software/crisporWebsite/bin/Darwin/bwa bwasw -T 20 /Users/elowe3/bioinformatics_software/crisporWebsite/genomes/sacCer3/sacCer3.fa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crisporBestMatchT56QC_.fa
[main] Real time: 0.022 sec; CPU: 0.020 sec
INFO:root:Progress x50sPGMoTvUagv3zWjGg - effScores - Calculating guide efficiency scores
INFO:root:Wrote eff scores to /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.effScores.tab
INFO:root:Progress x50sPGMoTvUagv3zWjGg - bwa - Alignment of potential guides, mismatches <= 4
[bwa_aln_core] calculate SA coordinate... 0.08 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 7 sequences have been processed.
[main] Version: 0.7.9a-r786
[main] CMD: /Users/elowe3/bioinformatics_software/crisporWebsite/bin/Darwin/bwa aln -o 0 -m 1980000 -n 4 -k 4 -N -l 20 ../genomes/sacCer3/sacCer3.fa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.fa
[main] Real time: 0.122 sec; CPU: 0.116 sec
INFO:root:Progress x50sPGMoTvUagv3zWjGg - saiToBed - Converting alignments
[bwa_aln_core] convert to sequence coordinate... 0.01 sec
[bwa_aln_core] refine gapped alignments... 0.00 sec
[bwa_aln_core] print alignments... 0.00 sec
[bwa_aln_core] 7 sequences have been processed.
[main] Version: 0.7.9a-r786
[main] CMD: /Users/elowe3/bioinformatics_software/crisporWebsite/bin/Darwin/bwa samse -n 60000 ../genomes/sacCer3/sacCer3.fa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.sa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.fa
[main] Real time: 0.047 sec; CPU: 0.046 sec
Traceback (most recent call last):
  File "../bin/samToBed", line 14, in <module>
    guideLen = int(sys.argv[2])
IndexError: list index out of range
ERROR:root:Error: could not run command set -o pipefail; /Users/elowe3/bioinformatics_software/crisporWebsite/bin/Darwin/bwa samse -n 60000 ../genomes/sacCer3/sacCer3.fa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.sa /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.fa | ../bin/xa2multi.pl | ../bin/samToBed NGG | sort -k1,1 -k2,2n | /Users/elowe3/bioinformatics_software/crisporWebsite/bin/Darwin/bedClip stdin ../genomes/sacCer3/sacCer3.sizes stdout >> /var/folders/bz/lbll3mbn29v8bpf5w2hfdfyngydffc/T/crispormG6saZ/x50sPGMoTvUagv3zWjGg.matches.bed .
```

**Comment by maximilianh** [comment]
Wow, this is strange! Are you really sure that you checked out the master
branch? I tried it with the current master branch and samToBed needs the
additional argument "20" now to work. In the current master branch, it's
"samToBed NGG 20", not "samToBed NGG". Are you using an old version?

I made this change half a year ago or so. I don't know how you downloaded
such an old version of the software.

**Comment by elijahlowe** [comment]
I got the same error, I even check to make sure I had the correct branch:

``` 
git checkout master
M	bin/Darwin/WU-CRISPR/result/sgOligo_V0.9_prediction_result.xls
D	genomes.sample/sacCer3/genomeInfo.tab
D	genomes.sample/sacCer3/sacCer3.2bit
D	genomes.sample/sacCer3/sacCer3.fa.amb
D	genomes.sample/sacCer3/sacCer3.fa.ann
D	genomes.sample/sacCer3/sacCer3.fa.bwt
D	genomes.sample/sacCer3/sacCer3.fa.pac
D	genomes.sample/sacCer3/sacCer3.fa.sa
D	genomes.sample/sacCer3/sacCer3.segments.bed
D	genomes.sample/sacCer3/sacCer3.sizes
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```
after that I deleted the repo and cloned it again but to no avail.

**Comment by maximilianh** [comment]
How about this command? Does this show the same line? Especially this
part: "$SCRIPT/samToBed %(pam)s %(seqLen)d"


$ grep "samToBed" crispor.py

    cmd = "$BIN/bwa samse -n %(maxOcc)d
%(genomeDir)s/%(genome)s/%(genome)s.fa %(saFname)s %(faFname)s |
$SCRIPT/xa2multi.pl | $SCRIPT/samToBed %(pam)s %(seqLen)d | sort -k1,1
-k2,2n | $BIN/bedClip stdin %(genomeDir)s/%(genome)s/%(genome)s.sizes
stdout >> %(matchesBedFname)s " % locals()

in my master branch, this is the file size:
$ ls -la crispor.py

-rwxrwxr-x 1 max max 291440 Mar  6 07:16 crispor.py

You're not on a fork, are you?

$ git remote -v

origin  git@github.com:maximilianh/crisporWebsite.git (fetch)

$ git status crispor.py
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

**Comment by elijahlowe** [comment]
All of them are the same, the output from grep:
```
grep "samToBed" crispor.py
cmd = "$BIN/bwa samse -n %(maxOcc)d %(genomeDir)s/%(genome)s/%(genome)s.fa %(saFname)s %(faFname)s | $SCRIPT/xa2multi.pl | $SCRIPT/samToBed %(pam)s %(seqLen)d | sort -k1,1 -k2,2n | $BIN/bedClip stdin %(genomeDir)s/%(genome)s/%(genome)s.sizes stdout >> %(matchesBedFname)s " % locals()
```
The file size:
```
ls -la crispor.py
-rwxr-xr-x  1 elowe3  AD\Domain Users  291440 Mar  8 09:21 crispor.py
```
And the branch:
```
git remote -v
origin	https://github.com/maximilianh/crisporWebsite.git (fetch)
origin	https://github.com/maximilianh/crisporWebsite.git (push)

git status crispor.py
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by maximilianh** [comment]
Oh wow, I'm erm... not tidy. Please replace "crispor.cgi" in the command
with "crispor.py" ? Apparently I still have a super old version of the
script in the repo! How weird that I've never seen it and no one else ever
pointed it out. Sorry! I'll clean up my repo now and fix the docs.

many thanks for pointing this out!

**Comment by elijahlowe** [comment]
yup, that did it. I'm surprised I didn't catch it myself. Thanks for the help.
